"""add lesson images

Revision ID: 4ee4df2c8faa
Revises: 7a21268a4295
Create Date: 2026-06-10 14:25:25.138616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee4df2c8faa'
down_revision = '7a21268a4295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('future_work_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('future_work_image')
        batch_op.drop_column('work_image')

    # ### end Alembic commands ###
